### ISSUE TITLE
Some Essential Question about Patch Independent

### ISSUE THREAD

**Issue by YangYu-NUAA** [seunghan96/pits#2]
Your work are digestible and interesting.
We **all** know that **currently** our Transformer or other DNNs cannot perfectly handle the complex relationship among all the features(channels) or among the historical and the future series which may lead to poor performance. Hence, channel independent method is a last resort approach. However, your patch independent method also deviates from the original intention of deep learning for time series prediction. If we further ignore the relationship between each patch to improve prediction performance a bit (from the forecasting results compared to PatchTST), it can only indicate that current deep learning methods cannot solve complex temporal dependence.

So I think it  may be more suitable for time series representation learning than forecasting.

**Comment by seunghan96** [comment]
I appreciate your interest in my research!

As you mentioned, our work can be seen as closer to "representation learning" rather than "forecasting."

From the perspective of representation learning, we believe that embedding vectors of each time series patch can be more beneficial when considered independently, without taking into account other patches.
However, from the forecasting perspective, we also believe that the key is to effectively combine well-learned patch embedding vectors through the proposed representation learning to achieve higher prediction performance! :)

**Comment by seunghan96** [comment]
I appreciate your interest in my research :)

As you mentioned, our research can be seen as closer to "representation learning" rather than "forecasting." 
From the perspective of representation learning, we believe that embedding vectors of each time series patch can be more beneficial when considered independently, without taking into account other patches. 
However, from the forecasting perspective, I also believe that the key is to effectively combine well-learned patch embedding vectors through the proposed representation learning to achieve higher prediction performance.

Additionally, we want to emphasize that our work is not aimed at proposing a state-of-the-art (SOTA) method in time series forecasting. Actually, it is counter-intuitive to ignore channel and patch dependencies, but our experiments show that the previous Transformer-based methods aiming to capture these dependencies do not perform well. This indicates that they do not effectively capture these relationships. 
Thus, we believe that our patch independent methodology becomes the baseline for future works and hope that algorithms based on patch dependencies that captures these relationships effectivly will emerge.
